db:
  password: big secret
mail:
  sender: dummy
spring:
  mail:
    host: smtp.gmail.com
    password: <login password to smtp server>
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: <login user to smtp server>
  main:
    allow-circular-references: true #hack to allow spring to use black magic to fix it. DONT
  datasource:
    hikari:
      auto-commit: true
john.name: John
welcome:
  help:
    file: c:/help-file.pdf
    app-id: 123
  localContactPhone:
    FR: 430123414123
    RO: 401312121414
  supportUrls:
    - http://google.com
    - http://stackoverflow.com
    - http://baeldung.com
    - http://spring.io
  welcome-message: Hello from Config Server

prod.stuff.only: 10
#mail.sender.dummy: true